version: '2'

services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=nutt.men --logLevel=DEBUG
    restart: always
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik

networks:
  web:
    external: true